version: 2.1

executors:
    node-executor:
        docker:
            - image: circleci/node:12
              environment:
                  CI: true

orbs:
    node: circleci/node@4.0.1

jobs:
    install:
        executor: node-executor
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn
            - persist_to_workspace:
                  root: .
                  paths: [./*]

    test:
        executor: node-executor
        steps:
            - attach_workspace:
                  at: .
            - run: yarn mobx build test
            - run: yarn lint
            - run: yarn test -i

    mobx:
        executor: node-executor
        steps:
            - attach_workspace:
                  at: .
            - run: yarn mobx build
            - run: yarn mobx test:flow
            - run: yarn mobx test:size
            - run:
                  command: yarn mobx test:performance
                  environment:
                      PERSIST: true
            - store_artifacts:
                  path: packages/mobx/perf_report
                  destination: mobx-perf
    mobx-react:
        executor: node-executor
        steps:
            - attach_workspace:
                  at: .
            - run: yarn mobx build test
            - run: yarn mobx test:size

workflows:
    version: 2
    main:
        jobs:
            - install
            - test:
                  requires: [install]
            - mobx:
                  requires: [install]
            - mobx-react:
                  requires: [install]